### ISSUE TITLE
installer 

### ISSUE THREAD

**Issue by drmarwat** [alchg/AlchgLinux#1]
Hi ,
When will be the new release issued and is it possible to add  calamares or abif to the install it to hard disk ?

**Comment by alchg** [comment]
They are released at the end or beginning of the month.
Installation using abif required modifications and manipulation of configuration files. calamares is unknown.
Thanks for the post.

**Comment by drmarwat** [comment]
Thanks for the reply
Agreed , I suggested abif for people who might want to install it , I have
already installed alchg to hard disk by abif and using it on daily basis as
an installed system
